sonar.projectKey=bluesentinelsec_vigil
sonar.organization=bluesentinelsec

sonar.sources=src,include
sonar.tests=tests,integration_tests
sonar.cfamily.build-wrapper-output=bw-output
sonar.sourceEncoding=UTF-8
