sonar.projectKey=bluesentinelsec_vigil
sonar.organization=bluesentinelsec

sonar.sources=src,include
sonar.tests=tests,integration_tests
sonar.sourceEncoding=UTF-8
sonar.coverageReportPaths=sonarqube-coverage.xml
