package interp

// registerStdlib registers built-in modules.
func (interp *Interpreter) registerStdlib() {
	interp.builtinModules["fmt"] = interp.makeFmtModule()
	interp.builtinModules["os"] = interp.makeOsModule()
	interp.builtinModules["math"] = interp.makeMathModule()
	interp.builtinModules["file"] = interp.makeFileModule()
	interp.builtinModules["ffi"] = interp.makeFfiModule()
	interp.builtinModules["unsafe"] = interp.makeUnsafeModule()
	interp.builtinModules["strings"] = interp.makeStringsModule()
	interp.builtinModules["time"] = interp.makeTimeModule()
	interp.builtinModules["path"] = interp.makePathModule()
	interp.builtinModules["log"] = interp.makeLogModule()
	interp.builtinModules["regex"] = interp.makeRegexModule()
	interp.builtinModules["json"] = interp.makeJsonModule()
	interp.builtinModules["xml"] = interp.makeXmlModule()
	interp.builtinModules["base64"] = interp.makeBase64Module()
	interp.builtinModules["hex"] = interp.makeHexModule()
	interp.builtinModules["csv"] = interp.makeCsvModule()
	interp.builtinModules["sort"] = interp.makeSortModule()
	interp.builtinModules["io"] = interp.makeIoModule()
	interp.builtinModules["archive"] = interp.makeArchiveModule()
	interp.builtinModules["compress"] = interp.makeCompressModule()
	interp.builtinModules["hash"] = interp.makeHashModule()
	interp.builtinModules["crypto"] = interp.makeCryptoModule()
	interp.builtinModules["rand"] = interp.makeRandModule()
	interp.builtinModules["tcp"] = interp.makeTcpModule()
	interp.builtinModules["udp"] = interp.makeUdpModule()
	interp.builtinModules["http"] = interp.makeHttpModule()
	interp.builtinModules["mime"] = interp.makeMimeModule()
	interp.builtinModules["sqlite"] = interp.makeSqliteModule()
	interp.builtinModules["args"] = interp.makeArgsModule()
	interp.builtinModules["thread"] = interp.makeThreadModule()
	interp.builtinModules["mutex"] = interp.makeMutexModule()
	interp.builtinModules["rl"] = interp.makeRaylibModule()
}
