package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func runEmbed(args []string) int {
	if wantsHelp(args) {
		fmt.Print(mustHelpText("embed"))
		return 0
	}

	output := ""
	compress := ""
	var targets []string

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "-o", "--output":
			i++
			if i >= len(args) {
				fmt.Fprintln(os.Stderr, "error: -o requires a filename")
				return 2
			}
			output = args[i]
		case "--compress":
			compress = "yes"
		case "--no-compress":
			compress = "no"
		default:
			targets = append(targets, args[i])
		}
	}

	if len(targets) == 0 {
		fmt.Fprintln(os.Stderr, "usage: basl embed <file|dir...> [-o output.basl]")
		return 2
	}

	// Determine mode: single file, multiple files, or directory
	if len(targets) == 1 {
		info, err := os.Stat(targets[0])
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %s\n", err)
			return 1
		}
		if info.IsDir() {
			return embedDir(targets[0], output, compress)
		}
		return embedSingle(targets[0], output, compress)
	}
	return embedMulti(targets, output, compress)
}

type embedEntry struct {
	relPath string // relative path key (forward slashes)
	data    []byte
}

func embedSingle(path, output, compressFlag string) int {
	data, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %s\n", err)
		return 1
	}

	baseName := filepath.Base(path)
	varName := sanitizeName(baseName)
	if output == "" {
		output = varName + ".basl"
	}

	useGzip := shouldCompress(data, compressFlag)
	encoded := encodeData(data, useGzip)

	var buf strings.Builder
	if useGzip {
		buf.WriteString("// generated by basl embed — do not edit (gzip+base64)\n")
		buf.WriteString("import \"base64\";\nimport \"compress\";\n\n")
	} else {
		buf.WriteString("// generated by basl embed — do not edit (base64)\n")
		buf.WriteString("import \"base64\";\n\n")
	}

	fmt.Fprintf(&buf, "pub string name = %q;\n", baseName)
	fmt.Fprintf(&buf, "pub i32 size = %d;\n\n", len(data))
	fmt.Fprintf(&buf, "string _b64 = %q;\n\n", encoded)

	buf.WriteString("pub fn bytes() -> (string, err) {\n")
	if useGzip {
		buf.WriteString("    string decoded, err e1 = base64.decode(_b64);\n")
		buf.WriteString("    string data, err e2 = compress.gunzip(decoded);\n")
		buf.WriteString("    return (data, e2);\n")
	} else {
		buf.WriteString("    string data, err e1 = base64.decode(_b64);\n")
		buf.WriteString("    return (data, e1);\n")
	}
	buf.WriteString("}\n")

	if err := os.WriteFile(output, []byte(buf.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error: %s\n", err)
		return 1
	}
	fmt.Printf("embedded %s → %s (%d bytes", baseName, output, len(data))
	if useGzip {
		fmt.Printf(", gzip+base64)\n")
	} else {
		fmt.Printf(", base64)\n")
	}
	return 0
}

func embedMulti(paths []string, output, compressFlag string) int {
	if output == "" {
		output = "assets.basl"
	}

	var entries []embedEntry
	for _, p := range paths {
		data, err := os.ReadFile(p)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %s\n", err)
			return 1
		}
		entries = append(entries, embedEntry{relPath: filepath.Base(p), data: data})
	}

	return writeMultiModule(entries, output, compressFlag)
}

func embedDir(dir, output, compressFlag string) int {
	if output == "" {
		output = sanitizeName(filepath.Base(dir)) + ".basl"
	}

	var entries []embedEntry
	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(dir, path)
		entries = append(entries, embedEntry{
			relPath: filepath.ToSlash(rel),
			data:    data,
		})
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %s\n", err)
		return 1
	}

	if len(entries) == 0 {
		fmt.Fprintln(os.Stderr, "error: no files found in directory")
		return 1
	}

	return writeMultiModule(entries, output, compressFlag)
}

func writeMultiModule(entries []embedEntry, output, compressFlag string) int {
	needsCompress := false
	type entryMeta struct {
		encoded string
		gzipped bool
	}
	metas := make([]entryMeta, len(entries))

	for i, e := range entries {
		gz := shouldCompress(e.data, compressFlag)
		metas[i] = entryMeta{encoded: encodeData(e.data, gz), gzipped: gz}
		if gz {
			needsCompress = true
		}
	}

	var buf strings.Builder
	fmt.Fprintf(&buf, "// generated by basl embed — do not edit\n")
	fmt.Fprintf(&buf, "// source: %d files\n", len(entries))
	buf.WriteString("import \"base64\";\n")
	if needsCompress {
		buf.WriteString("import \"compress\";\n")
	}
	buf.WriteString("\n")

	// Blob variables
	for i, m := range metas {
		fmt.Fprintf(&buf, "string _%d = %q;\n", i, m.encoded)
	}
	buf.WriteString("\n")

	// get(path) function
	buf.WriteString("pub fn get(string path) -> (string, err) {\n")
	for i, e := range entries {
		fmt.Fprintf(&buf, "    if (path == %q) {\n", e.relPath)
		if metas[i].gzipped {
			fmt.Fprintf(&buf, "        string decoded, err e1 = base64.decode(_%d);\n", i)
			buf.WriteString("        string data, err e2 = compress.gunzip(decoded);\n")
			buf.WriteString("        return (data, e2);\n")
		} else {
			fmt.Fprintf(&buf, "        string data, err e1 = base64.decode(_%d);\n", i)
			buf.WriteString("        return (data, e1);\n")
		}
		buf.WriteString("    }\n")
	}
	buf.WriteString("    return (\"\", err(\"embed: not found: \" + path));\n")
	buf.WriteString("}\n\n")

	// list() function
	buf.WriteString("pub fn list() -> array<string> {\n")
	buf.WriteString("    return [")
	for i, e := range entries {
		if i > 0 {
			buf.WriteString(", ")
		}
		fmt.Fprintf(&buf, "%q", e.relPath)
	}
	buf.WriteString("];\n")
	buf.WriteString("}\n\n")

	fmt.Fprintf(&buf, "pub i32 count = %d;\n", len(entries))

	if err := os.WriteFile(output, []byte(buf.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error: %s\n", err)
		return 1
	}

	totalSize := 0
	for _, e := range entries {
		totalSize += len(e.data)
	}
	fmt.Printf("embedded %d files → %s (%d bytes total)\n", len(entries), output, totalSize)
	return 0
}

func encodeData(data []byte, useGzip bool) string {
	if useGzip {
		var buf bytes.Buffer
		w := gzip.NewWriter(&buf)
		w.Write(data)
		w.Close()
		return base64.StdEncoding.EncodeToString(buf.Bytes())
	}
	return base64.StdEncoding.EncodeToString(data)
}

func shouldCompress(data []byte, flag string) bool {
	if flag == "yes" {
		return true
	}
	if flag == "no" {
		return false
	}
	// Auto: compress if gzip saves >=10%
	if len(data) < 64 {
		return false
	}
	var buf bytes.Buffer
	w := gzip.NewWriter(&buf)
	w.Write(data)
	w.Close()
	return buf.Len() < len(data)*9/10
}

func sanitizeName(name string) string {
	name = strings.TrimSuffix(name, filepath.Ext(name))
	var b strings.Builder
	for i, c := range name {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_' {
			b.WriteRune(c)
		} else if c >= '0' && c <= '9' {
			if i == 0 {
				b.WriteRune('_')
			}
			b.WriteRune(c)
		} else {
			b.WriteRune('_')
		}
	}
	s := b.String()
	if s == "" {
		return "embedded"
	}
	return s
}
